version: "3.9"

services:
  iam-api-db:
    image: postgres:16.1
    container_name: iam-postgres
    environment:
      - POSTGRES_DB=iam
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iam-password
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U postgres"

  keycloak-db:
    image: postgres:16.1
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=keycloak-password
    ports:
      - "5432"
    healthcheck:
      test: "pg_isready -U postgres"
    labels:
      org.springframework.boot.ignore: true

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=keycloak-password
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
    command: start-dev --import-realm
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
      test: "curl -f http://localhost:8080/health/ready || exit 1"
    labels:
      org.springframework.boot.ignore: true

  iam-api:
    image: omidmk567/iam-aas:1.0.0
    container_name: iam-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://iam-postgres:5432/iam
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iam-password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - APP_IAM_AAS_KEYCLOAK_BASE_URL=http://keycloak:8080
      - APP_IAM_AAS_KEYCLOAK_MASTER_REALM=master
      - APP_IAM_AAS_KEYCLOAK_MASTER_USERNAME=admin
      - APP_IAM_AAS_KEYCLOAK_MASTER_PASSWORD=admin
      - APP_IAM_AAS_KEYCLOAK_MASTER_CLIENT_ID=admin-cli
      - APP_IAM_AAS_KEYCLOAK_AUTH_REALM=IAM-aaS
    depends_on:
      - iam-api-db
      - keycloak
    ports:
      - "8000:8000"